postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_DB: simplenotebook    
    POSTGRES_USER: simplenotebook
    POSTGRES_PASSWORD: mypassword
  ports:
    - '5432:5432'
  volumes:
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

simplenotebook-client:
  build: ./sn-client/
  ports:
    - "80:80"

simplenotebook-server-python:
  build: ./sn-server-python/
  command: gunicorn -b 0.0.0.0:5000 --reload --access-logfile - "sn-server-python.app:app"
  environment:
    PYTHONUNBUFFERED: 1
  links:
    - postgres
  volumes:
    - .:/simplenotebook
  ports:
    - '5000:5000'
